spring:
  application:
    name: food-delivery-platform

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:food_delivery}
    username: ${POSTGRES_USER:food_user}
    password: ${POSTGRES_PASSWORD:food_password}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog.yml
    default-schema: ${APP_SCHEMA:food_app}
    liquibase-schema: ${LIQUIBASE_SCHEMA:liquibase_meta}
    parameters:
      appSchema: ${APP_SCHEMA:food_app}

server:
  port: 8080

logging:
  level:
    root: INFO
    com.dima.fooddelivery: DEBUG
    liquibase: INFO
    net.lbruun.springboot.preliquibase: TRACE